server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      mvc:
        routes:
          - id: USER-SERVICE
            uri: lb://USER-SERVICE
            predicates:
              - path=/user/**
          - id: VEHICAL-SERVICE
            uri: lb://VEHICAL-SERVICE
            predicates:
              - path=/vehicle/**
          - id: TICKET-SERVICE
            uri: lb://TICKET-SERVICE
            predicates:
              - path=/ticket/**
